"""Write hood/src/ReplicatedStorage/Shared/Models/GunModels.lua and IconModels.lua from the BoxKit models.

Plain Python (no Blender needed):  python3 hood/tools/blender/export_luau.py
Rojo syncs the two modules into ReplicatedStorage.Shared.Models, which is how the models reach Studio.
"""
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import boxkit as bk  # noqa: E402
from models import guns, icons  # noqa: E402

HOOD = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT_DIR = os.path.join(HOOD, 'src', 'ReplicatedStorage', 'Shared', 'Models')
MAX_PARTS = 120

# Material kind -> Roblox look. Kept in the generated module (M.Materials) so it can be retuned there.
ROBLOX_MAT = {
	'plastic': ('Plastic', 0, 0, True),
	'smooth': ('SmoothPlastic', 0, 0, True),
	'metal': ('Metal', 0, 0, True),
	'gold': ('Foil', 0, 0, True),
	'neon': ('Neon', 0, 0, False),
	'glass': ('Glass', 0.2, 0.35, False),
}
KIND_ORDER = list(bk.KINDS)
SHAPE_CODE = {'Block': 'B', 'Wedge': 'W', 'Cylinder': 'C', 'Ball': 'S'}

# Camera direction used for the renders (Roblox space, model -> camera); IconModels.viewport uses it.
GUN_VIEW = (1.0, 0.42, -0.42)
ICON_VIEW = (-0.32, 0.36, -1.0)


def num(x):
	"""Short, stable number text."""
	if abs(x) < 5e-5:
		return '0'
	s = '%.4f' % x
	s = s.rstrip('0').rstrip('.')
	return '-0' if s == '-0' else s


def vec(v):
	return 'Vector3.new(%s, %s, %s)' % tuple(num(c) for c in v)


def model_rows(m, colors, rots):
	rows = []
	for p in m.roblox_parts():
		c = colors.setdefault(p['color'], len(colors) + 1)
		rkey = tuple(round(v, 5) for row in p['rot'] for v in row)
		ident = all(abs(rkey[i] - (1 if i in (0, 4, 8) else 0)) < 1e-6 for i in range(9))
		r = 1 if ident else rots.setdefault(rkey, len(rots) + 2)
		u = m.unit
		vals = [
			"'%s'" % SHAPE_CODE[p['shape']], str(c), str(KIND_ORDER.index(p['mat']) + 1),
			num(p['size'][0] * u), num(p['size'][1] * u), num(p['size'][2] * u),
			num(p['pos'][0] * u), num(p['pos'][1] * u), num(p['pos'][2] * u),
			str(r), "'%s'" % (p['name'] or 'Part'),
		]
		rows.append('{' + ', '.join(vals) + '}')
	return rows


def bounds_studs(m):
	lo, hi = m.bounds()
	u = m.unit
	size = tuple((hi[i] - lo[i]) * u for i in range(3))
	centre = tuple((hi[i] + lo[i]) / 2 * u for i in range(3))
	return size, centre


HEADER = '''-- GENERATED by hood/tools/blender/export_luau.py from hood/tools/blender/models/{src}.py. Do not edit by
-- hand: change the model code, then re-run the exporter (see .claude/skills/blender-roblox-models).
-- {what}
-- The parts here are exactly the BoxKit primitives the Blender renders were made from.
--   M.build(id, scale?) -> Model   {origin}
--   M.weld(model) -> Model         unanchors and welds every part to the PrimaryPart (for held Tools)
--   M.viewport(id, size?) -> ViewportFrame   live 3D preview, framed like the Blender render
--   M.Ids, M.Images (id -> uploaded rbxassetid of the render, '' until uploaded), M.Meta, M.Materials
local M = {{}}
'''

BODY = '''
-- Material kinds -> Roblox look. Retune here to restyle every model at once.
M.Materials = {
%(materials)s
}
local KINDS = { %(kinds)s }

local COLORS = {
%(colors)s
}

-- Rotation matrices (row-major, as in CFrame.new(x, y, z, r00, ..., r22)); 1 is identity.
local ROTS = {
	{ 1, 0, 0, 0, 1, 0, 0, 0, 1 },
%(rots)s
}

-- One row per part: shape (B block, W wedge, C cylinder along local X, S ball), colour, material kind,
-- size x, y, z, position x, y, z (studs at scale 1), rotation, name.
local DATA = {
%(data)s
}

local MIN_SIZE = 0.001 -- Roblox's smallest part dimension

local function makePart(row, s: number): BasePart
	local shape = row[1]
	local part: BasePart
	if shape == 'W' then
		part = Instance.new('WedgePart')
	else
		local p = Instance.new('Part')
		if shape == 'C' then
			p.Shape = Enum.PartType.Cylinder
		elseif shape == 'S' then
			p.Shape = Enum.PartType.Ball
		end
		part = p
	end
	local kindName = KINDS[row[3]]
	local kind = M.Materials[kindName]
	part.Name = row[11]
	part.Size = Vector3.new(math.max(row[4] * s, MIN_SIZE), math.max(row[5] * s, MIN_SIZE), math.max(row[6] * s, MIN_SIZE))
	local r = ROTS[row[10]]
	part.CFrame = CFrame.new(row[7] * s, row[8] * s, row[9] * s, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9])
	part.Color = COLORS[row[2]]
	part.Material = kind.Material
	part.Reflectance = kind.Reflectance
	part.Transparency = kind.Transparency
	-- Studs and glowing/see-through parts cast no shadow: cheaper and cleaner on small props.
	part.CastShadow = kind.CastShadow and row[11] ~= 'Stud'
	part.TopSurface = Enum.SurfaceType.Smooth
	part.BottomSurface = Enum.SurfaceType.Smooth
	part.Anchored = true
	part.CanCollide = false
	part.CanTouch = false
	part.CanQuery = false
	return part
end

function M.build(id: string, scale: number?): Model
	local rows = DATA[id]
	assert(rows, '%(module)s: unknown id ' .. tostring(id))
	local s = scale or 1
	local model = Instance.new('Model')
	model.Name = id
	-- Invisible root at the origin: PrimaryPart and pivot (%(rootwhy)s).
	local root = Instance.new('Part')
	root.Name = '%(root)s'
	root.Size = Vector3.new(0.2, 0.2, 0.2) * s
	root.CFrame = CFrame.new()
	root.Transparency = 1
	root.CastShadow = false
	root.Anchored = true
	root.CanCollide = false
	root.CanTouch = false
	root.CanQuery = false
	root.Parent = model
	for _, row in rows do
		makePart(row, s).Parent = model
	end
	model.PrimaryPart = root
	model:SetAttribute('ModelId', id)
	model:SetAttribute('Scale', s)
	return model
end

function M.weld(model: Model): Model
	local root = model.PrimaryPart
	assert(root, 'weld: model has no PrimaryPart')
	for _, d in model:GetDescendants() do
		if d:IsA('BasePart') and d ~= root then
			local w = Instance.new('WeldConstraint')
			w.Part0 = root
			w.Part1 = d
			w.Parent = d
			d.Anchored = false
			d.Massless = true
		end
	end
	root.Anchored = false
	return model
end

M.View = %(view)s -- direction from the model toward the camera in the Blender renders

function M.viewport(id: string, size: UDim2?): ViewportFrame
	local meta = M.Meta[id]
	assert(meta, '%(module)s: unknown id ' .. tostring(id))
	local vf = Instance.new('ViewportFrame')
	vf.Name = id
	vf.Size = size or UDim2.fromScale(1, 1)
	vf.BackgroundTransparency = 1
	vf.Ambient = Color3.fromRGB(170, 170, 180)
	vf.LightColor = Color3.fromRGB(255, 248, 235)
	vf.LightDirection = Vector3.new(0.6, -1, 0.5)
	local model = M.build(id, 1)
	model.Parent = vf
	local cam = Instance.new('Camera')
	cam.FieldOfView = 30
	local radius = meta.Size.Magnitude / 2
	local dist = radius / math.tan(math.rad(cam.FieldOfView / 2)) * 1.05
	cam.CFrame = CFrame.lookAt(meta.Center + M.View.Unit * dist, meta.Center)
	cam.Parent = vf
	vf.CurrentCamera = cam
	return vf
end

return M
'''


def existing_images(path):
	"""Keep image ids already pasted into M.Images when the module is regenerated."""
	if not os.path.exists(path):
		return {}
	text = open(path).read()
	block = re.search(r'M\.Images = \{(.*?)\n\}', text, re.S)
	if not block:
		return {}
	return dict(re.findall(r"(\w+) = '([^']*)'", block.group(1)))


def write_module(path, module, models, src, what, origin, root, rootwhy, view, extra_meta):
	keep = existing_images(path)
	colors, rots = {}, {}
	data_blocks, meta_lines = [], []
	for m in models:
		rows = model_rows(m, colors, rots)
		if len(rows) > MAX_PARTS:
			raise SystemExit('%s has %d parts (limit %d)' % (m.id, len(rows), MAX_PARTS))
		data_blocks.append('\t%s = {\n%s\n\t},' % (m.id, '\n'.join('\t\t' + r + ',' for r in rows)))
		size, centre = bounds_studs(m)
		fields = ["Name = '%s'" % m.name, 'Parts = %d' % (len(rows) + 1), 'Size = %s' % vec(size), 'Center = %s' % vec(centre)]
		fields += extra_meta(m)
		meta_lines.append('\t%s = { %s },' % (m.id, ', '.join(fields)))
	ids = ', '.join("'%s'" % m.id for m in models)
	images = '\n'.join("\t%s = '%s', -- %s" % (m.id, keep.get(m.id, ''), m.name) for m in models)
	materials = '\n'.join("\t%s = { Material = Enum.Material.%s, Reflectance = %s, Transparency = %s, CastShadow = %s }," % (k, v[0], num(v[1]), num(v[2]), 'true' if v[3] else 'false') for k, v in ((k, ROBLOX_MAT[k]) for k in KIND_ORDER))
	color_lines = '\n'.join('\tColor3.fromRGB(%d, %d, %d),' % c for c, _ in sorted(colors.items(), key=lambda kv: kv[1]))
	rot_lines = '\n'.join('\t{ %s },' % ', '.join(num(v) for v in r) for r, _ in sorted(rots.items(), key=lambda kv: kv[1]))
	text = HEADER.format(src=src, what=what, origin=origin)
	text += 'M.Ids = { %s }\n' % ids
	text += '-- Paste the uploaded image ids of hood/art/%s renders here (rbxassetid://...).\nM.Images = {\n%s\n}\n' % ('renders/guns' if module == 'GunModels' else 'icons3d', images)
	text += 'M.Unit = %s -- studs per BoxKit design unit at scale 1 (one stud bump pitch)\n' % num(models[0].unit if module == 'GunModels' else 0.2)
	text += 'M.Meta = {\n%s\n}\n' % '\n'.join(meta_lines)
	text += BODY % dict(materials=materials, kinds=', '.join("'%s'" % k for k in KIND_ORDER), colors=color_lines, rots=rot_lines,
		data='\n'.join(data_blocks), module=module, root=root, rootwhy=rootwhy, view=vec(bk.norm(view)))
	with open(path, 'w') as f:
		f.write(text)
	return len(text)


def main():
	os.makedirs(OUT_DIR, exist_ok=True)
	gun_models = guns.build_all()
	icon_models = icons.build_all()
	problems = []
	for m in gun_models + icon_models:
		problems += bk.lint(m)
	for p in problems:
		print('lint:', p)

	def gun_meta(m):
		u = m.unit
		mz = m.meta['muzzle']
		return ['Tier = %d' % m.meta['tier'], 'Muzzle = %s' % vec(tuple(c * u for c in mz))]

	n = write_module(os.path.join(OUT_DIR, 'GunModels.lua'), 'GunModels', gun_models, 'guns',
		'The 10 armory guns (Config/Guns.lua ids), tier 1 to 10.',
		'origin at the grip, muzzle toward -Z, up +Y; scale 1 = held in a hand (pistol ~1.5 studs)',
		'Handle', 'the grip; weld Tool parts to it', GUN_VIEW, gun_meta)
	print('GunModels.lua', n, 'bytes', [(m.id, m.part_count() + 1) for m in gun_models])

	def icon_meta(m):
		return ['Unit = %s' % num(m.unit)]

	n = write_module(os.path.join(OUT_DIR, 'IconModels.lua'), 'IconModels', icon_models, 'icons',
		'The 9 HUD icons as 3D models (Shop, Rebirth, Rewards, PVP, Evolve, Cash, Power, Trophy, Gun).',
		'centred on the origin, fits a 2x2x2 stud box at scale 1, front faces -Z',
		'Root', 'the centre of the icon', ICON_VIEW, icon_meta)
	print('IconModels.lua', n, 'bytes', [(m.id, m.part_count() + 1) for m in icon_models])
	return 1 if problems else 0


if __name__ == '__main__':
	sys.exit(main())
