#!/usr/bin/env python3
"""Bundle the map modules + a mock Roblox API into one runnable Luau file.

The Luau CLI has no filesystem access, so the only way to actually EXECUTE the
map builders outside Studio is to concatenate everything into a single script.
Requires are rewritten to a registry lookup keyed on the last path component
(`require(ReplicatedStorage.Shared.Config.Balance)` -> `__require("Balance")`).
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

MODULES = {
    "Balance":  SRC / "ReplicatedStorage/Shared/Config/Balance.luau",
    "Palettes": SRC / "ReplicatedStorage/Shared/Config/Palettes.luau",
    "Rivals":   SRC / "ReplicatedStorage/Shared/Config/Rivals.luau",
    "Ranks":    SRC / "ReplicatedStorage/Shared/Config/Ranks.luau",
    "Floors":   SRC / "ReplicatedStorage/Shared/Config/Floors.luau",
    "Format":   SRC / "ReplicatedStorage/Shared/Util/Format.luau",
    "Kit":      SRC / "ServerScriptService/Server/World/Kit.luau",
    "Gear":      SRC / "ReplicatedStorage/Shared/Config/Gear.luau",
    "Interns":   SRC / "ReplicatedStorage/Shared/Config/Interns.luau",
    "Severance": SRC / "ReplicatedStorage/Shared/Config/Severance.luau",
    "Sanitize":  SRC / "ReplicatedStorage/Shared/Util/Sanitize.luau",
    # The multiplier stack: pure math, no DataModel access, so it runs headless.
    "Stack":     SRC / "ServerScriptService/Server/Economy/Stack.luau",
}
FLOOR_IDS = ["Mailroom", "CubicleFarm", "OpenPlan", "Executive", "Penthouse", "OrbitalHQ"]
for fid in FLOOR_IDS:
    MODULES[fid] = SRC / f"ServerScriptService/Server/World/Floors/{fid}.luau"

REQUIRE_RE = re.compile(r"require\(\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\)")


def rewrite(source: str) -> str:
    # require(a.b.C) -> __require("C")
    source = REQUIRE_RE.sub(lambda m: '__require("%s")' % m.group(1).split(".")[-1], source)
    # `export type` is illegal inside a function body, and we wrap every module.
    source = source.replace("export type ", "type ")
    # Service handles resolve through the mock `game`.
    source = re.sub(r"game:GetService\(", "__game:GetService(", source)
    return source


def build(test_body: str) -> str:
    out = ["--!nonstrict", "-- GENERATED by tools/build_harness.py — do not edit.", ""]

    mock = (ROOT / "tools/roblox_mock.luau").read_text()
    out.append("local __mock = (function()\n%s\nend)()\n" % mock)
    for name in ("Vector2", "Vector3", "CFrame", "Color3", "UDim", "UDim2", "Enum", "Instance"):
        out.append(f"local {name} = __mock.{name}")
    out.append("local __game = __mock.game\n")

    out.append("local __registry = {}")
    out.append("local __loaded = {}")
    out.append("""
local function __require(name)
	if __loaded[name] ~= nil then return __loaded[name] end
	local factory = __registry[name]
	if factory == nil then error("harness: no module registered as '" .. name .. "'") end
	local result = factory()
	__loaded[name] = result
	return result
end
""")

    for name, path in MODULES.items():
        if not path.exists():
            sys.exit(f"missing module: {path}")
        out.append('__registry["%s"] = function()\n%s\nend\n' % (name, rewrite(path.read_text())))

    out.append(test_body)
    return "\n".join(out)


if __name__ == "__main__":
    body = pathlib.Path(sys.argv[1]).read_text()
    dest = pathlib.Path(sys.argv[2])
    dest.write_text(build(body))
    print(f"wrote {dest} ({dest.stat().st_size // 1024} KB)")
